routes/web.php
<?php
Route::get('/', function () { return redirect('/admin/home'); });

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {
    Route::get('/home', 'HomeController@index');
    Route::resource('abilities', 'Admin\AbilitiesController');
    Route::post('abilities_mass_destroy', ['uses' => 'Admin\AbilitiesController@massDestroy', 'as' => 'abilities.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);


    Route::resource('clientes', 'ClientesController');
    Route::post('clientes_mass_destroy', ['uses' => 'ClientesController@massDestroy', 'as' => 'clientes.mass_destroy']);

     Route::resource('clientese', 'ClienteseController');
    Route::post('clientese_mass_destroy', ['uses' => 'ClienteseController@massDestroy', 'as' => 'clientese.mass_destroy']);

    Route::resource('eventos', 'EventosController');
    Route::post('eventos_mass_destroy', ['uses' => 'EventosController@massDestroy', 'as' => 'eventos.mass_destroy']);

      Route::resource('llamados', 'LlamadosController');
    Route::post('llamados_mass_destroy', ['uses' => 'LlamadosController@massDestroy', 'as' => 'llamados.mass_destroy']);


    Route::resource('confirmar', 'ConfirmarController');
    Route::post('confirmar_mass_destroy', ['uses' => 'ConfirmarController@massDestroy', 'as' => 'confirmar.mass_destroy']);

    Route::resource('empresas', 'Admin\EmpresasController');
    Route::post('empresas_mass_destroy', ['uses' => 'Archivos\EmpresasController@massDestroy', 'as' => 'empresas.mass_destroy']);

     Route::resource('pagos', 'PagosController');
    Route::post('pagos_mass_destroy', ['uses' => 'PagosController@massDestroy', 'as' => 'pagos.mass_destroy']);

        Route::resource('asistencia', 'AsistenciaController');
    Route::post('asistencia_mass_destroy', ['uses' => 'AsistenciaController@massDestroy', 'as' => 'asistencia.mass_destroy']);

});
    Route::get('/clientes/index1','ClientesController@index1')->name('admin.clientes.index1');
    Route::get('/clientes-llamar-{id}','ClientesController@llamar');

    Route::get('/clientes-rellamar-{id}','ClientesController@rellamar');
    Route::put('/rellamar','ClientesController@rellamarpost')->name('admin.rellamar.update');
    Route::get('/rellamados','ClientesController@indexRellamados')->name('admin.rellamados');



    Route::get('/llamados/index1','LlamadosController@index1')->name('admin.llamados.index1');
    Route::get('/confirmar/index1','ConfirmarController@index1')->name('admin.confirmar.index1');

        Route::get('/asistencia/index1','AsistenciaController@index1')->name('admin.asistencia.index1');



    

  Route::get('reportes/llamadas','ReportesController@llamadas')->name('index.llamadas');
  Route::get('reportes/ingresos','ReportesController@ingresos')->name('index.ingresos');
  Route::get('reportes/asistentes','ReportesController@asistentes')->name('index.asistentes');

  Route::get('listado_llamadas','ReportesController@listado_llamadas_ver')->name('listado_llamadas_ver');
  Route::get('listado_ingresos','ReportesController@listado_ingresos_ver')->name('listado_ingresos_ver');
  Route::get('listado_asistentes','ReportesController@listado_asistentes_ver')->name('listado_asistentes_ver');




  Route::get('listado_atenciondiaria_ver','Reportes\PdfController@listado_atenciondiaria_ver')->name('listado_atenciondiaria_ver');
  Route::get('/historia_pacientes_ver/{id}','Reportes\PdfController@historia_pacientes_ver');
  Route::get('/recibo_profesionales_ver/{id}','Reportes\PdfController@recibo_profesionales_ver');
  Route::get('/resultados_ver/{id}','Reportes\PdfController@resultados_ver')->name('resultados');
  Route::get('/resultados_lab_ver/{id}','Reportes\PdfController@resultados_lab_ver')->name('resultados_lab');
  Route::get('/resultados_lab_paq_ver/{id}','Reportes\PdfController@resultados_lab_paq_ver')->name('resultados_lab_paq');
  Route::get('/resultados_lab_paq_serv_ver/{id}','Reportes\PdfController@resultados_lab_paq_serv')->name('resultados_lab_paq_serv');

app/Eventos.php
<?php
namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Silber\Bouncer\Database\HasRolesAndAbilities;
use Hash;

/**
 * Class Centrosmedicos
 *
 * @package App
 * @property string $nombre
 * @property string $descripcion
 * @property string $responsable
 * @property string $capacidad
  * @property string $usuario
    * @property string $fecha

*/
class Eventos extends Authenticatable
{
    use Notifiable;
    use HasRolesAndAbilities;

    protected $fillable = ['nombre', 'descripcion', 'responsable','capacidad','fecha','usuario'];
    
    
   
    
    
}

app/Http/Controllers/EventosController.php
<?php

namespace App\Http\Controllers;

use App\Eventos;
use DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Auth;


class EventosController extends Controller
{
    /**
     * Display a listing of User.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        

         $eventos = DB::table('eventos as a')
        ->select('a.id','a.nombre','a.responsable','a.fecha','a.descripcion','a.capacidad','a.usuario','b.name')
        ->join('users as b','b.id','a.usuario')
        ->get();

        return view('eventos.index', compact('eventos'));
    }

    /**
     * Show the form for creating new User.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       

        return view('eventos.create');
    }

    /**
     * Store a newly created User in storage.
     *
     * @param  \App\Http\Requests\StoreUsersRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        

         $id_usuario = Auth::id();

          $validator = \Validator::make($request->all(), [
          'nombre' => 'required|string|max:255',
  
          
        ]);

    
       $eventos = new Eventos;
       $eventos->nombre =$request->nombre;
       $eventos->descripcion     =$request->descripcion;
       $eventos->capacidad     =$request->capacidad;
       $eventos->fecha     =$request->fecha;
       $eventos->responsable     =$request->responsable;
       $eventos->usuario = Auth::id();
       $eventos->save();


        return redirect()->route('admin.eventos.index');
        return redirect()->back()->with("success", "EL EVENTO FUE REGISTRADO EXITOSAMENTE");

    }


    /**
     * Show the form for editing User.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        

        $eventos = Eventos::findOrFail($id);

        return view('eventos.edit', compact('eventos'));
    }

    /**
     * Update User in storage.
     *
     * @param  \App\Http\Requests\UpdateUsersRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        


        $eventos = Eventos::findOrFail($id);
        $eventos->update($request->all());

   
       
        return redirect()->route('admin.eventos.index');
    }

    /**
     * Remove User from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       
        $eventos = Eventos::findOrFail($id);
        $eventos->delete();

        return redirect()->route('admin.eventos.index');
    }

    /**
     * Delete all selected User at once.
     *
     * @param Request $request
     */
    public function massDestroy(Request $request)
    {
        
        if ($request->input('ids')) {
            $entries = Eventos::whereIn('id', $request->input('ids'))->get();

            foreach ($entries as $entry) {
                $entry->delete();
            }
        }
    }

}

resources/views/eventos/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Eventos</h3>
    {!! Form::open(['method' => 'POST', 'route' => ['admin.eventos.store']]) !!}
    @include("messages.messages")


    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_create')
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('nombre', 'Nombre de Evento*', ['class' => 'control-label']) !!}
                    {!! Form::text('nombre', old('nombre'), ['class' => 'form-control', 'placeholder' => 'Nombres', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('nombre'))
                        <p class="help-block">
                            {{ $errors->first('nombre') }}
                        </p>
                    @endif
                </div>
                </div>
                <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('descripcion', 'Descrpciòn', ['class' => 'control-label']) !!}
                    {!! Form::text('descripcion', old('descripcion'), ['class' => 'form-control', 'placeholder' => 'Descripciòn de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('descripcion'))
                        <p class="help-block">
                            {{ $errors->first('descripcion') }}
                        </p>
                    @endif
                </div>
            </div>

             <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('responsable', 'Responsable', ['class' => 'control-label']) !!}
                    {!! Form::text('responsable', old('responsable'), ['class' => 'form-control', 'placeholder' => 'Responsable de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('responsable'))
                        <p class="help-block">
                            {{ $errors->first('responsable') }}
                        </p>
                    @endif
                </div>
            </div>

          </div>

          <div class="row">

              <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('fecha', 'Fecha', ['class' => 'control-label']) !!}
                    {!! Form::date('fecha', old('fecha'), ['class' => 'form-control', 'placeholder' => 'Fecha de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('fecha'))
                        <p class="help-block">
                            {{ $errors->first('fecha') }}
                        </p>
                    @endif
                </div>
            </div>

             <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('capacidad', 'Capacidad', ['class' => 'control-label']) !!}
                    {!! Form::text('capacidad', old('capacidad'), ['class' => 'form-control', 'placeholder' => 'Capacidad de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('capacidad'))
                        <p class="help-block">
                            {{ $errors->first('capacidad') }}
                        </p>
                    @endif
                </div>
            </div>
              

          </div>
     
        
         
        
        </div>
    </div>

    {!! Form::submit(trans('global.app_save'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/eventos/edit.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Modificar Evento</h3>
    
    {!! Form::model($eventos, ['method' => 'PUT', 'route' => ['admin.eventos.update', $eventos->id]]) !!}

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_edit')
        </div>
  <div class="panel-body">
            <div class="row">
                <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('nombre', 'Nombre de Evento*', ['class' => 'control-label']) !!}
                    {!! Form::text('nombre', old('nombre'), ['class' => 'form-control', 'placeholder' => 'Nombres', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('nombre'))
                        <p class="help-block">
                            {{ $errors->first('nombre') }}
                        </p>
                    @endif
                </div>
                </div>
                <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('descripcion', 'Descrpciòn', ['class' => 'control-label']) !!}
                    {!! Form::text('descripcion', old('descripcion'), ['class' => 'form-control', 'placeholder' => 'Descripciòn de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('descripcion'))
                        <p class="help-block">
                            {{ $errors->first('descripcion') }}
                        </p>
                    @endif
                </div>
            </div>

             <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('responsable', 'Responsable', ['class' => 'control-label']) !!}
                    {!! Form::text('responsable', old('responsable'), ['class' => 'form-control', 'placeholder' => 'Responsable de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('responsable'))
                        <p class="help-block">
                            {{ $errors->first('responsable') }}
                        </p>
                    @endif
                </div>
            </div>

          </div>

          <div class="row">

              <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('fecha', 'Fecha', ['class' => 'control-label']) !!}
                    {!! Form::date('fecha', old('fecha'), ['class' => 'form-control', 'placeholder' => 'Fecha de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('fecha'))
                        <p class="help-block">
                            {{ $errors->first('fecha') }}
                        </p>
                    @endif
                </div>
            </div>

             <div class="col-md-4">
                <div class="col-xs-12 form-group">
                    {!! Form::label('capacidad', 'Capacidad', ['class' => 'control-label']) !!}
                    {!! Form::text('capacidad', old('capacidad'), ['class' => 'form-control', 'placeholder' => 'Capacidad de Evento', 'required' => 'false']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('capacidad'))
                        <p class="help-block">
                            {{ $errors->first('capacidad') }}
                        </p>
                    @endif
                </div>
            </div>
              

          </div>
     
        
         
        
        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/eventos/index.blade.php
@inject('request', 'Illuminate\Http\Request')
@extends('layouts.app')

@section('content')
    <h3 class="page-title">Eventos</h3>
    <p>
        <a href="{{ route('admin.eventos.create') }}" class="btn btn-success" style="background: #DF01A5;">@lang('global.app_add_new')</a>
    </p>

    <div class="panel panel-default">
        <div class="panel-heading">
            @lang('global.app_list')
        </div>

        <div class="panel-body table-responsive">
            <table class="table table-bordered table-striped {{ count($eventos) > 0 ? 'datatable' : '' }} dt-select">
                <thead>
                    <tr>
                        <th style="text-align:center;"><input type="checkbox" id="select-all" /></th>

                        <th>Nombre del Evento</th>
                        <th>Descripcion</th>
                        <th>Fecha</th>
                        <th>Capacidad</th>
                        <th>Responsable</th>
                        <th>Registrado Por:</th>
                        <th>&nbsp;</th>

                    </tr>
                </thead>
                
                <tbody>
                    @if (count($eventos) > 0)
                        @foreach ($eventos as $ctr)
                            <tr data-entry-id="{{ $ctr->id }}">
                                <td></td>

                                <td>{{ $ctr->nombre }}</td>
                                <td>{{ $ctr->descripcion }}</td>
                                <td>{{ $ctr->fecha }}</td>
                                <td>{{ $ctr->capacidad }}</td>
                                <td>{{ $ctr->responsable }}</td>
                                <td>{{ $ctr->name }}</td>

                                <td>
                                    <a href="{{ route('admin.eventos.edit',[$ctr->id]) }}" class="btn btn-xs btn-info">@lang('global.app_edit')</a>
                                    {!! Form::open(array(
                                        'style' => 'display: inline-block;',
                                        'method' => 'DELETE',
                                        'onsubmit' => "return confirm('".trans("global.app_are_you_sure")."');",
                                        'route' => ['admin.eventos.destroy', $ctr->id])) !!}
                                    {!! Form::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger')) !!}
                                    {!! Form::close() !!}
                                </td>

                            </tr>
                        @endforeach
                    @else
                        <tr>
                            <td colspan="9">@lang('global.app_no_entries_in_table')</td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
    </div>
@stop

@section('javascript') 
    <script>
        window.route_mass_crud_entries_destroy = '{{ route('admin.clientes.mass_destroy') }}';
    </script>
@endsection